server:
  port: 8083

#配置rabbitMq 服务器
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: huangyan
    password: huangyan123

#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huangyan?&useUnicode=true&characterEncoding=UTF-8
    username: user
    password: 123456

#mybatis-plus配置     此处注释掉仍然可以找到mapper的映射xml????
#mybatis-plus:
  #mapper-location: classpath:mapper/*.xml


#mybatis配置
#mybatis:
  #mapper-locations: classpath:mapper/*.xml

#redis
  redis:
    host: localhost
  #Redis服务器连接端口
    port: 6379
  #Redis服务器连接密码（默认为空）
    password: 123456
    timeout: 3000


#控制台打印sql
logging:
  level:
    com:
      example:
        rabbitmqproducer:
          mapper: DEBUG
