server:
  port: 8083

#配置rabbitMq 服务器
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/huangyan?&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

#mybatis-plus配置
#mybatis-plus:
  #mapper-location: classpath:mapper/*.xml
  #config-location: classpath:mapper/*.xml


#mybatis配置
#mybatis:
  #mapper-locations: classpath:mapper/*.xml


#控制台打印sql
logging:
  level:
    com:
      example:
        rabbitmqproducer:
          mapper: DEBUG
