server:
  port: 8083

#配置rabbitMq 服务器
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: huangyan
    password: huangyan123

#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huangyan?&useUnicode=true&characterEncoding=UTF-8
    username: user
    password: 123456

  #redis
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 3000

#mybatis-plus配置     此处注释掉仍然可以找到mapper的映射xml????
mybatis-plus:
  mapper-location: classpath:mapper/*.xml
  configuration:
    cache-enabled: true      #使用缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #控制台输出

  #mybatis配置
#mybatis:
  #mapper-locations: classpath:mapper/*.xml





#控制台打印sql
logging:
  level:
    com:
      example:
        rabbitmqproducer:
          mapper: DEBUG
